#  Start db: docker-compose up db
#  Start app: AWS_KEY=<key> AWS_SECRET=<secret> docker-compose up app
#  Stop all: docker-compose down (add -v to wipe db)

version: '3.7'

volumes:
  db_data:

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  DB_HOST: db
  DB_NAME: mydb
  DB_USER: myuser
  DB_PASS: mypass

services:
  app:
    image: my-project:latest
    build:
      context: .
    environment:
      <<: *shared_environment
      FS_NAME: vaportestbucket
      FS_REGION: us-west-1
    depends_on:
      - db
    ports:
      - '8080:8080'

  db:
    image: postgres:12.2-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
