#if !canImport(ObjectiveC)
import XCTest

extension SubtopicApiTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SubtopicApiTests = [
        ("testCreateSubtopics", testCreateSubtopics),
        ("testGetSubtopics", testGetSubtopics),
        ("testUpdateSubtopic", testUpdateSubtopic),
    ]
}

extension TopicApiTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TopicApiTests = [
        ("testCreateTopics", testCreateTopics),
        ("testGetTopics", testGetTopics),
        ("testUpdateTopic", testUpdateTopic),
    ]
}

extension VideoApiTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VideoApiTests = [
        ("testCreateVideos", testCreateVideos),
        ("testGetVideos", testGetVideos),
        ("testUpdateVideos", testUpdateVideos),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SubtopicApiTests.__allTests__SubtopicApiTests),
        testCase(TopicApiTests.__allTests__TopicApiTests),
        testCase(VideoApiTests.__allTests__VideoApiTests),
    ]
}
#endif
